### ISSUE TITLE
EmberCLI app "frontend" has failed to build

### ISSUE THREAD

**Issue by gohdan** [hummingbird-me/hummingbird#688]
I've followed "Setting up a development environment" guide but after step 3 ("Start the application") I receive an error "EmberCLI::App::BuildError: EmberCLI app "frontend" has failed to build" when I go to the application port with browser. Any clues what could it be and how it could be fixed?

```
EmberCLI::App::BuildError
EmberCLI app "frontend" has failed to build

Rails.root: /opt/hummingbird
Application Trace | Framework Trace | Full Trace

Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at NodeWatcher.watchdir (frontend/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:144:20)
    at new NodeWatcher (frontend/node_modules/ember-cli/node_modules/sane/src/node_watcher.js:45:8)
    at new sane (frontend/node_modules/ember-cli/node_modules/sane/index.js:16:12)
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (frontend/node_modules/ember-cli/node_modules/broccoli-sane-watcher/index.js:93:17)
    at frontend/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:67:35
    at lib$rsvp$$internal$$tryCatch (frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (frontend/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)

Request

Parameters:

None

Toggle session dump

Toggle env dump

HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "ru,en-US;q=0.7,en;q=0.3"
HTTP_CACHE_CONTROL: "max-age=0"
REMOTE_ADDR: "--- my IP address here ---"
SERVER_NAME: "--- my server name here ---"
SERVER_PROTOCOL: "HTTP/1.1"

Response

Headers:

None
```

**Comment by NuckChorris** [comment]
`ENOSPC` means "error: no space" generally. Do you have space on that disk?

**Comment by nivla** [comment]
I have the same error, but the log looks like this. any clue?
```
BuildingBuilding.Building...
20:12:49 unicorn.1 | ENOENT: no such file or directory, scandir 'node_modules/ember-cli-ic-ajax/node_modules/'
20:12:49 unicorn.1 | Error: ENOENT: no such file or directory, scandir 'node_modules/ember-cli-ic-ajax/node_modules/'
20:12:49 unicorn.1 |     at Error (native)
20:12:49 unicorn.1 |     at Object.fs.readdirSync (fs.js:856:18)
20:12:49 unicorn.1 |     at /home/voyager/work/github/hummingbird/frontend/node_modules/broccoli-merge-trees/index.js:32:21
20:12:49 unicorn.1 |     at Array.map (native)
20:12:49 unicorn.1 |     at mergeRelativePath (/home/voyager/work/github/hummingbird/frontend/node_modules/broccoli-merge-trees/index.js:30:29)
20:12:49 unicorn.1 |     at /home/voyager/work/github/hummingbird/frontend/node_modules/broccoli-merge-trees/index.js:23:5
20:12:49 unicorn.1 |     at lib$rsvp$$internal$$tryCatch (/home/voyager/work/github/hummingbird/frontend/node_modules/rsvp/dist/rsvp.js:493:16)
20:12:49 unicorn.1 |     at lib$rsvp$$internal$$invokeCallback (/home/voyager/work/github/hummingbird/frontend/node_modules/rsvp/dist/rsvp.js:505:17)
20:12:49 unicorn.1 |     at lib$rsvp$$internal$$publish (/home/voyager/work/github/hummingbird/frontend/node_modules/rsvp/dist/rsvp.js:476:11)
20:12:49 unicorn.1 |     at lib$rsvp$asap$$flush (/home/voyager/work/github/hummingbird/frontend/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by pixeldesu** [comment]
ENOSPC is also something that occurs when the systems max. `inotify` watch limit is reached. I fixed this with raising the limit, the errors and warnings weren't occuring after this anymore.

**Comment by NuckChorris** [comment]
Will (probably) be fixed in V3
