### ISSUE TITLE
bin/rake importers:kitsu:covers not working

### ISSUE THREAD

**Issue by DNA** [hummingbird-me/hummingbird#786]
```
lprado:~/Code/kitsu (the-future) > bin/rake "importers:kitsu:covers[200]"
=> Grabbing anime covers
Getting unimported list...
Found 12598! Prioritizing popular series and limiting...
Importing 200!
Downloading files...
rake aborted!
NoMethodError: undefined method `options' for nil:NilClass
/opt/kitsu/server/lib/data_import/kitsu.rb:83:in `request_url'
/opt/kitsu/server/lib/data_import/kitsu.rb:68:in `block in get'
/usr/local/bundle/gems/typhoeus-1.0.2/lib/typhoeus/request/callbacks.rb:104:in `block in execute_headers_callbacks'
/usr/local/bundle/gems/typhoeus-1.0.2/lib/typhoeus/request/callbacks.rb:103:in `map'
/usr/local/bundle/gems/typhoeus-1.0.2/lib/typhoeus/request/callbacks.rb:103:in `execute_headers_callbacks'
/usr/local/bundle/gems/typhoeus-1.0.2/lib/typhoeus/easy_factory.rb:155:in `block in set_callback'
/usr/local/bundle/gems/ethon-0.9.0/lib/ethon/easy/response_callbacks.rb:43:in `block in headers'
/usr/local/bundle/gems/ethon-0.9.0/lib/ethon/easy/response_callbacks.rb:43:in `each'
/usr/local/bundle/gems/ethon-0.9.0/lib/ethon/easy/response_callbacks.rb:43:in `headers'
/usr/local/bundle/gems/ethon-0.9.0/lib/ethon/easy/callbacks.rb:41:in `block in body_write_callback'
/usr/local/bundle/gems/ethon-0.9.0/lib/ethon/multi/operations.rb:174:in `multi_perform'
/usr/local/bundle/gems/ethon-0.9.0/lib/ethon/multi/operations.rb:174:in `trigger'
/usr/local/bundle/gems/ethon-0.9.0/lib/ethon/multi/operations.rb:163:in `run'
/usr/local/bundle/gems/ethon-0.9.0/lib/ethon/multi/operations.rb:43:in `perform'
/usr/local/bundle/gems/typhoeus-1.0.2/lib/typhoeus/hydra/runnable.rb:15:in `run'
/usr/local/bundle/gems/typhoeus-1.0.2/lib/typhoeus/hydra/memoizable.rb:51:in `run'
/opt/kitsu/server/lib/data_import/kitsu.rb:4:in `run'
/opt/kitsu/server/lib/tasks/importers.rake:45:in `block in get_anime_image'
/usr/local/bundle/gems/chewy-0.8.4/lib/chewy/strategy.rb:60:in `wrap'
/usr/local/bundle/gems/chewy-0.8.4/lib/chewy.rb:179:in `strategy'
/opt/kitsu/server/lib/tasks/importers.rake:20:in `get_anime_image'
/opt/kitsu/server/lib/tasks/importers.rake:14:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => importers:kitsu:covers
(See full trace by running task with --trace)
```

This error occurs within the `request_url` method used when a Request fail. Now I'm trying to discover why it's happening, I hope to send a PR soon :)

**Comment by NuckChorris** [comment]
The API it uses is dead anyways.  I've been thinking of just making Paperclip point at our media server and then providing an escape hatch to enable local storage of images 🤔
